---
appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.devcontainer/Dockerfile:
  delete: true
.devcontainer/devcontainer.json:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: voxpupuli-puppet-lint-plugins
        platforms: ruby
        version: '>= 3.0'
Rakefile:
  linter_fail_on_warnings: true
